# Generated by Django 5.2.15 on 2026-07-01 03:11

import courses.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the department.', max_length=150, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Short description of the department.')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the course.', max_length=200)),
                ('code', models.CharField(help_text='Unique course code, e.g. CS101.', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Course code must be 2-4 uppercase letters followed by 2-4 digits (e.g. CS101).', regex='^[A-Z]{2,4}\\d{2,4}$')])),
                ('credits', models.PositiveIntegerField(help_text='Number of academic credits (1-10).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10), courses.validators.validate_credits])),
                ('department', models.ForeignKey(help_text='Department that offers this course.', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.department')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the student.', max_length=150)),
                ('email', models.EmailField(help_text='Unique email address of the student.', max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, default='', help_text='Contact phone number.', max_length=15, validators=[django.core.validators.RegexValidator(message="Enter a valid phone number (7-15 digits, optional leading '+').", regex='^\\+?\\d{7,15}$')])),
                ('department', models.ForeignKey(help_text='Department the student belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='students', to='courses.department')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_on', models.DateTimeField(auto_now_add=True, help_text='Timestamp of enrollment.')),
                ('course', models.ForeignKey(help_text='Course the student is enrolling in.', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
                ('student', models.ForeignKey(help_text='Student being enrolled.', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.student')),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
                'ordering': ['-enrolled_on'],
                'constraints': [models.UniqueConstraint(fields=('student', 'course'), name='unique_student_course_enrollment')],
            },
        ),
    ]
